workflows:
  build-android:
    name: Build Android APK only
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        JAVA_TOOL_OPTIONS: "-Xmx4096m"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Generate code (build_runner)
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
