workflows:
  build-mobile:
    name: Build APK and IPA
    max_build_duration: 60
    environment:
      flutter: 3.7.2
      xcode: latest
      vars:
        JAVA_TOOL_OPTIONS: "-Xmx4096m"
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
      - name: Build IPA
        script: flutter build ipa --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa
